### PR TITLE
Hotfix/exit code

### PR DESCRIPTION
**Pull request by brunogui0812**
Make zmbackup not exit code 0 on backup error

### CODE REVIEW

**Comment by lucascbeyeler** [comment]
@brunogui0812 Good afternoon,

I'm going to review all the modifications you are proposing and before the end of this week I merge with the main code.

Thanks for your support.

Regards,
Lucas Costa Beyeler

**Comment by brunogui0812** [comment]
OK @lucascbeyeler.

You can ignore the commit "adad21a", because I've reverted this on the "164edb3" commit. 

Thank you and I hope that my modifications can help the project.

**Comment by lucascbeyeler** [comment]
@brunogui0812, Good Morning

Could you provide some explanations about some of the modifications you did? Like why autoincrement is a bug and why you made empty files as a error?

**Comment by brunogui0812** [comment]
Hi @lucascbeyeler,

- Autoincrement - I was getting error importing sql file to my database. So I did some research and figured out that if a colum is primary key, theres no need to pass "autoincrement" parameter.

- Empty File - I've reverted this situation on commit "164edb3". Initialy I don't understood why the app was considering empty file as OK. But after some tests I realized that it is for incremental files. You can discard this change.

**Comment by lucascbeyeler** [comment]
I'm closing this issue because I can't include inside the main code. Sorry for the news.

About the problem trying to import "database.sql": The autoincrement is a valid option for SQLITE, the only database that I gave support for now. If you are trying to use inside different databases you will have some problems...

Here is the link: https://sqlite.org/autoinc.html

About the other modifications, some of them I liked and I will include inside the code, but I can't insert all of them. They doesn't make sense inside Zmbackup logic. I will create a doc about how to develop later.

Anyway, thanks for your support!

Regards
Lucas Costa Beyeler

**Comment by brunogui0812** [comment]
no problem @lucascbeyeler! thank's for your answer!

**Pull request closed without merging**
