### PR TITLE
Some adjusts

### PR DESCRIPTION
**Pull request by ananiasfilho**
We found some bugs using new zimbra 8.8.9.
wget options to download files (--http-user, --http-passwd, --auth-no-challenge)
FQDN/HOSTNAME - get full hostname of machine
IP ADDRESS of server - its return domain host ip instead hostname ip address.
Inlcude ZMBKP_MAIL_SENDER var to be included into zmbackup.conf

### CODE REVIEW

**Comment by ananiasfilho** [comment]
More FIX
1 - include option '-p' to create OSE_DEFAULT_BKP_DIR recursively.
2 - check if table return 0 data from backup_account table and start backup.

**Review by lucascbeyeler — COMMENTED** [review]
I think this fix should be made a little different before I aproved:

1) The message is in portuguese, we need to keep the language as english because there is foreigners who use this software.

2) If I understand correctly, the problem here is that the Zmbackup is not checking if the folder exist, right? If this is the problem the message make clear that you should remove the Zmbackup to install, even if the correctly problem is that the folder already exist. I think you should change this message to something else.

3) I would remove the "else" from this "if" condition and made to check if is not equal. This is necessary because this way you broke the loading bar.

Sorry if I sound like a Tirant, but this change I found a little confuse so I want to clarify before aprove :)

Regards,
Lucas Costa Beyeler

**Review by lucascbeyeler — APPROVED** [review]
Aproved!

**Review by lucascbeyeler — APPROVED** [review]
I think you misspelled OS_INSTALL_DOMAIN to OSE_INSTALL_HOSTNAME. Anyway aproved too!

Regards,
Lucas Costa Beyeler

**Review by lucascbeyeler — APPROVED** [review]
APROVED

**Comment by lucascbeyeler** [comment]
After the modification needed as we talked, all the code is included inside the Zmbackup. Thanks for your help @ananiasfilho 

Regards,
Lucas Costa Beyeler

**Pull request merged**
